### ISSUE TITLE
Добавить относительные ссылки внутри документа

### ISSUE THREAD

**Issue by Nps-rf** [GnuriaN/format-README.md#4]
**Как насчет того чтобы сделать дополнение по относительным ссылкам?**
**Например:**
## Оглавление
* [**Используемые технологии**](#используемые-технологии)
* [**Как пользоваться?**](#как-пользоваться)
* [**О проекте**](#о-проекте)
  * [**Deploy**](#deploy)
  * [**Структура**](#структура)
* [**А что ещё есть?**](#а-что-ещё-есть)
* [**Иллюстрации**](#иллюстрации)
```
* [**Используемые технологии**](#используемые-технологии)
* [**Как пользоваться?**](#как-пользоваться)
* [**О проекте**](#о-проекте)
  * [**Deploy**](#deploy)
  * [**Структура**](#структура)
* [**А что ещё есть?**](#а-что-ещё-есть)
* [**Иллюстрации**](#иллюстрации)
```

**Далее будут заголовки**

# Используемые технологии
#### Структура

------

**Comment by GnuriaN** [comment]
Все необходимы ссылки в документе есть. Я не совсем понимаю, что именно не хватает.

**Comment by Nps-rf** [comment]
> Все необходимы ссылки в документе есть. Я не совсем понимаю, что именно не хватает.

Так я говорю про ссылки по тексту внутри документа которые задаются через # в круглых скобках

**Comment by Nps-rf** [comment]
Я пример привел выше
